// electron/youtubeSession.cjs — in-app YouTube sign-in.
//
// Opens a real YouTube login window inside the app using its own persistent
// session partition, then exports that partition's cookies to a Netscape
// cookies.txt in userData so yt-dlp can be run with `--cookies <file>`.
// Nothing leaves the machine, no OAuth app or external service is involved,
// and cookie VALUES never reach the renderer — only booleans and a path.
const { app, BrowserWindow, session } = require("electron");
const path = require("node:path");
const fs = require("node:fs");
const fsp = require("node:fs/promises");

const PARTITION = "persist:youtube";
const SIGNIN_URL = "https://accounts.google.com/ServiceLogin?service=youtube";
// Presence of any of these means a usable signed-in YouTube session.
const AUTH_COOKIES = ["SID", "__Secure-3PSID", "__Secure-1PSID"];

function ytSession() {
  return session.fromPartition(PARTITION);
}

function cookieFilePath() {
  return path.join(app.getPath("userData"), "yt-cookies.txt");
}

async function readAuthCookies() {
  const s = ytSession();
  const jars = await Promise.all([
    s.cookies.get({ domain: ".youtube.com" }),
    s.cookies.get({ domain: ".google.com" }),
  ]);
  const seen = new Set();
  const all = [];
  for (const cookie of jars.flat()) {
    const key = `${cookie.domain}|${cookie.path}|${cookie.name}`;
    if (seen.has(key)) continue;
    seen.add(key);
    all.push(cookie);
  }
  return all;
}

function hasAuth(cookies) {
  return cookies.some(
    (c) => AUTH_COOKIES.includes(c.name) && c.value && c.value.length > 0,
  );
}

function toNetscape(cookies) {
  const lines = [
    "# Netscape HTTP Cookie File",
    "# Generated by YouTube Clipper — local use only.",
    "",
  ];
  for (const c of cookies) {
    const domain = c.domain.startsWith(".") ? c.domain : `.${c.domain}`;
    const expires = c.expirationDate
      ? Math.floor(c.expirationDate)
      : Math.floor(Date.now() / 1000) + 60 * 60 * 24 * 180;
    lines.push(
      [
        domain,
        "TRUE",
        c.path || "/",
        c.secure ? "TRUE" : "FALSE",
        String(expires),
        c.name,
        c.value,
      ].join("\t"),
    );
  }
  return `${lines.join("\n")}\n`;
}

/** Writes the current partition cookies to disk. Returns true when signed in. */
async function exportCookieFile() {
  const cookies = await readAuthCookies();
  if (!hasAuth(cookies)) return false;
  const target = cookieFilePath();
  await fsp.writeFile(target, toNetscape(cookies), { mode: 0o600 });
  try {
    await fsp.chmod(target, 0o600);
  } catch {
    /* best effort on Windows */
  }
  return true;
}

/** Cheap check used on launch — no network call. */
async function probe() {
  try {
    const cookies = await readAuthCookies();
    const connected = hasAuth(cookies);
    if (connected) await exportCookieFile();
    const filePath = cookieFilePath();
    return {
      connected: connected && fs.existsSync(filePath),
      path: connected ? filePath : null,
    };
  } catch (err) {
    return {
      connected: false,
      path: null,
      error: err && err.message ? err.message : "Probe failed",
    };
  }
}

let loginWindow = null;

/**
 * Opens the sign-in window and resolves once a YouTube session exists (or the
 * user closes the window). The window closes itself on success.
 */
function openLoginWindow(parent, validate, onEvent) {
  const trace = (msg) => {
    if (typeof onEvent === "function") {
      try {
        onEvent(msg);
      } catch {
        /* logging must never break sign-in */
      }
    }
  };

  if (loginWindow && !loginWindow.isDestroyed()) {
    loginWindow.focus();
    return Promise.resolve({ connected: false, cancelled: true, path: null });
  }

  return new Promise((resolve) => {
    let win;
    try {
      win = new BrowserWindow({
        width: 520,
        height: 720,
        parent: parent && !parent.isDestroyed() ? parent : undefined,
        modal: false,
        show: true,
        title: "Sign in to YouTube",
        autoHideMenuBar: true,
        webPreferences: {
          partition: PARTITION,
          contextIsolation: true,
          nodeIntegration: false,
          sandbox: true,
        },
      });
    } catch (err) {
      trace(`window failed: ${err && err.message ? err.message : "unknown"}`);
      resolve({
        connected: false,
        cancelled: true,
        path: null,
        error: "Could not open the sign-in window.",
      });
      return;
    }
    loginWindow = win;
    trace("sign-in window opened");

    let settled = false;
    let lastError = null;
    let destroyed = false;
    let timer = null;
    let validationInFlight = false;

    const stopTimer = () => {
      if (timer) {
        clearInterval(timer);
        timer = null;
      }
    };

    const alive = () => !destroyed && win && !win.isDestroyed();

    const setTitleSafely = (title) => {
      if (!alive()) return;
      try {
        win.setTitle(title);
      } catch {
        /* window went away mid-call */
      }
    };

    const finish = async (connected) => {
      if (settled) return;
      settled = true;
      stopTimer();
      let saved = false;
      try {
        saved = connected ? await exportCookieFile() : false;
      } catch (err) {
        trace(`cookie export failed: ${err && err.message ? err.message : "unknown"}`);
        saved = false;
      }
      if (alive()) {
        try {
          win.close();
        } catch {
          /* already closing */
        }
      }
      loginWindow = null;
      trace(connected ? `finished connected=${saved}` : "finished cancelled");
      resolve({
        connected: saved,
        cancelled: !connected,
        path: saved ? cookieFilePath() : null,
        error: saved ? undefined : lastError || undefined,
      });
    };

    const check = async () => {
      if (validationInFlight || settled || !alive()) return;
      try {
        const cookies = await readAuthCookies();
        if (!hasAuth(cookies) || settled || !alive()) return;
        validationInFlight = true;
        trace("cookies found, verifying");
        setTitleSafely("Verifying YouTube…");
        const saved = await exportCookieFile();
        let verified = saved;
        if (saved && typeof validate === "function") {
          const outcome = await validate(cookieFilePath());
          if (outcome && typeof outcome === "object") {
            verified = !!outcome.ok;
            lastError = outcome.ok ? null : outcome.message || null;
          } else {
            verified = !!outcome;
            if (!verified) lastError = null;
          }
        } else if (!saved) {
          lastError = "YouTube did not hand over a usable session.";
        }
        // The window may have been closed while verification was running.
        if (settled || !alive()) return;
        if (verified) {
          trace("verified");
          await finish(true);
          return;
        }
        trace("verification rejected, staying open");
        setTitleSafely("Sign in to YouTube");
      } catch (err) {
        lastError = err && err.message ? err.message : null;
        trace(`check failed: ${err && err.message ? err.message : "unknown"}`);
      } finally {
        validationInFlight = false;
      }
    };

    win.webContents.on("did-navigate", () => void check());
    win.webContents.on("did-navigate-in-page", () => void check());
    win.webContents.on("render-process-gone", (_e, details) => {
      trace(`sign-in renderer gone reason=${details && details.reason}`);
      destroyed = true;
      stopTimer();
      void finish(false);
    });
    win.on("unresponsive", () => trace("sign-in window unresponsive"));
    timer = setInterval(() => void check(), 1500);
    win.on("closed", () => {
      destroyed = true;
      stopTimer();
      loginWindow = null;
      void finish(false);
    });

    win.loadURL(SIGNIN_URL).catch((err) => {
      trace(`load failed: ${err && err.message ? err.message : "unknown"}`);
      void finish(false);
    });
  });
}


async function clear() {
  try {
    await ytSession().clearStorageData();
  } catch {
    /* ignore */
  }
  try {
    await fsp.rm(cookieFilePath(), { force: true });
  } catch {
    /* ignore */
  }
  return { ok: true };
}

module.exports = { openLoginWindow, probe, clear, cookieFilePath };
