// electron/youtubeSession.cjs — in-app YouTube sign-in.
//
// Opens a real YouTube login window inside the app using its own persistent
// session partition, then exports that partition's cookies to a Netscape
// cookies.txt in userData so yt-dlp can be run with `--cookies <file>`.
// Nothing leaves the machine, no OAuth app or external service is involved,
// and cookie VALUES never reach the renderer — only booleans and a path.
const { app, BrowserWindow, session } = require("electron");
const path = require("node:path");
const fs = require("node:fs");
const fsp = require("node:fs/promises");

const PARTITION = "persist:youtube";
const SIGNIN_URL = "https://accounts.google.com/ServiceLogin?service=youtube";
// Presence of any of these means a usable signed-in YouTube session.
const AUTH_COOKIES = ["SID", "__Secure-3PSID", "__Secure-1PSID"];

function ytSession() {
  return session.fromPartition(PARTITION);
}

function cookieFilePath() {
  return path.join(app.getPath("userData"), "yt-cookies.txt");
}

async function readAuthCookies() {
  const s = ytSession();
  const jars = await Promise.all([
    s.cookies.get({ domain: ".youtube.com" }),
    s.cookies.get({ domain: ".google.com" }),
  ]);
  const seen = new Set();
  const all = [];
  for (const cookie of jars.flat()) {
    const key = `${cookie.domain}|${cookie.path}|${cookie.name}`;
    if (seen.has(key)) continue;
    seen.add(key);
    all.push(cookie);
  }
  return all;
}

function hasAuth(cookies) {
  return cookies.some(
    (c) => AUTH_COOKIES.includes(c.name) && c.value && c.value.length > 0,
  );
}

function toNetscape(cookies) {
  const lines = [
    "# Netscape HTTP Cookie File",
    "# Generated by YouTube Clipper — local use only.",
    "",
  ];
  for (const c of cookies) {
    const domain = c.domain.startsWith(".") ? c.domain : `.${c.domain}`;
    const expires = c.expirationDate
      ? Math.floor(c.expirationDate)
      : Math.floor(Date.now() / 1000) + 60 * 60 * 24 * 180;
    lines.push(
      [
        domain,
        "TRUE",
        c.path || "/",
        c.secure ? "TRUE" : "FALSE",
        String(expires),
        c.name,
        c.value,
      ].join("\t"),
    );
  }
  return `${lines.join("\n")}\n`;
}

/** Writes the current partition cookies to disk. Returns true when signed in. */
async function exportCookieFile() {
  const cookies = await readAuthCookies();
  if (!hasAuth(cookies)) return false;
  const target = cookieFilePath();
  await fsp.writeFile(target, toNetscape(cookies), { mode: 0o600 });
  try {
    await fsp.chmod(target, 0o600);
  } catch {
    /* best effort on Windows */
  }
  return true;
}

/** Cheap check used on launch — no network call. */
async function probe() {
  try {
    const cookies = await readAuthCookies();
    const connected = hasAuth(cookies);
    if (connected) await exportCookieFile();
    const filePath = cookieFilePath();
    return {
      connected: connected && fs.existsSync(filePath),
      path: connected ? filePath : null,
    };
  } catch (err) {
    return {
      connected: false,
      path: null,
      error: err && err.message ? err.message : "Probe failed",
    };
  }
}

let loginWindow = null;

/**
 * Opens the sign-in window and resolves once a YouTube session exists (or the
 * user closes the window). The window closes itself on success.
 */
function openLoginWindow(parent, validate) {
  if (loginWindow && !loginWindow.isDestroyed()) {
    loginWindow.focus();
    return Promise.resolve({ connected: false, cancelled: true, path: null });
  }

  return new Promise((resolve) => {
    const win = new BrowserWindow({
      width: 520,
      height: 720,
      parent: parent || undefined,
      modal: false,
      show: true,
      title: "Sign in to YouTube",
      autoHideMenuBar: true,
      webPreferences: {
        partition: PARTITION,
        contextIsolation: true,
        nodeIntegration: false,
        sandbox: true,
      },
    });
    loginWindow = win;

    let settled = false;
    let timer = null;
    let validationInFlight = false;
    const finish = async (connected) => {
      if (settled) return;
      settled = true;
      if (timer) clearInterval(timer);
      let saved = false;
      try {
        saved = connected ? await exportCookieFile() : false;
      } catch {
        saved = false;
      }
      if (!win.isDestroyed()) win.close();
      loginWindow = null;
      resolve({
        connected: saved,
        cancelled: !connected,
        path: saved ? cookieFilePath() : null,
      });
    };

    const check = async () => {
      if (validationInFlight) return;
      try {
        const cookies = await readAuthCookies();
        if (!hasAuth(cookies)) return;
        validationInFlight = true;
        win.setTitle("Verifying YouTube…");
        const saved = await exportCookieFile();
        const verified = saved && typeof validate === "function"
          ? await validate(cookieFilePath())
          : saved;
        if (verified) {
          await finish(true);
          return;
        }
        win.setTitle("Sign in to YouTube");
      } catch {
        /* keep polling */
      } finally {
        validationInFlight = false;
      }
    };

    win.webContents.on("did-navigate", () => void check());
    win.webContents.on("did-navigate-in-page", () => void check());
    timer = setInterval(() => void check(), 1500);
    win.on("closed", () => {
      loginWindow = null;
      void finish(false);
    });

    win.loadURL(SIGNIN_URL).catch(() => void finish(false));
  });
}

async function clear() {
  try {
    await ytSession().clearStorageData();
  } catch {
    /* ignore */
  }
  try {
    await fsp.rm(cookieFilePath(), { force: true });
  } catch {
    /* ignore */
  }
  return { ok: true };
}

module.exports = { openLoginWindow, probe, clear, cookieFilePath };
