/**
 * File: PreviewPanel.tsx
 * Path: src/components/PreviewPanel.tsx
 * Description: Right-column panel: video iframe and transcript view, swapped with animation.
 */
import { AnimatePresence, motion } from "framer-motion";
import {
  BsCameraVideo,
  BsFileText,
  BsClipboardCheck,
} from "react-bootstrap-icons";
import { useClipperContext } from "../context/ClipperContext";
import { formatTimestamp } from "../lib/clip";

export default function PreviewPanel() {
  const {
    info,
    videoId,
    showTranscript,
    toggleTranscript,
    loadingTranscript,
    transcript,
    rangeTranscript,
    copyTranscript,
  } = useClipperContext();

  const toggleClass =
    "flex items-center gap-2 border border-white px-3 py-2 hover:bg-white hover:text-black disabled:cursor-not-allowed disabled:opacity-50 disabled:hover:bg-black disabled:hover:text-white";

  return (
    <div className="flex min-w-0 flex-col gap-4">
      <div className="flex gap-3">
        <button
          type="button"
          onClick={toggleTranscript}
          disabled={!info}
          className={toggleClass}
        >
          {showTranscript ? <BsCameraVideo /> : <BsFileText />}
          <span>{showTranscript ? "View video" : "View transcript"}</span>
        </button>
        {showTranscript && (
          <button
            type="button"
            onClick={copyTranscript}
            disabled={rangeTranscript.length === 0}
            className={toggleClass}
          >
            <BsClipboardCheck />
            <span>Copy</span>
          </button>
        )}
      </div>

      <div className="relative aspect-video w-full border border-white bg-black">
        <AnimatePresence mode="wait">
          {showTranscript ? (
            <motion.div
              key="transcript"
              initial={{ opacity: 0, y: 6 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -6 }}
              transition={{ duration: 0.18 }}
              className="absolute inset-0 overflow-y-auto p-3 leading-relaxed"
            >
              {loadingTranscript ? (
                <span className="opacity-60">Loading transcript…</span>
              ) : rangeTranscript.length > 0 ? (
                <>
                  {rangeTranscript.map((l, i) => (
                    <p key={i} className="mb-2">
                      <span className="mr-2 opacity-50">
                        {formatTimestamp(l.start)}
                      </span>
                      {l.text}
                    </p>
                  ))}
                  <p className="mt-3 text-xs opacity-40">
                    Auto-generated by YouTube — may contain errors.
                  </p>
                </>
              ) : transcript && transcript.length === 0 ? (
                <span className="opacity-60">
                  No transcript available for this video.
                </span>
              ) : (
                <span className="opacity-60">
                  No lines in the selected range.
                </span>
              )}
            </motion.div>
          ) : (
            <motion.div
              key="video"
              initial={{ opacity: 0, y: 6 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -6 }}
              transition={{ duration: 0.18 }}
              className="absolute inset-0 flex items-center justify-center"
            >
              {videoId ? (
                <iframe
                  src={`https://www.youtube.com/embed/${videoId}`}
                  title="YouTube preview"
                  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                  allowFullScreen
                  className="h-full w-full border-0"
                />
              ) : (
                <span className="opacity-60">preview</span>
              )}
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}